kong:
  image:
    repository: quay.io/fiware/kong
    tag: "0.5.7"
    pullPolicy: IfNotPresent

  replicaCount: 1

  autoscaling:
    enabled: false

  env:
    database: "off"
    nginx_worker_processes: "2"
    proxy_access_log: /dev/stdout
    admin_access_log: /dev/stdout
    admin_gui_access_log: /dev/stdout
    portal_api_access_log: /dev/stdout
    proxy_error_log: /dev/stderr
    admin_error_log: /dev/stderr
    admin_gui_error_log: /dev/stderr
    portal_api_error_log: /dev/stderr
    prefix: /kong_prefix/
    log_level: debug
    nginx_proxy_large_client_header_buffers: "16 128k"
    nginx_proxy_http2_max_field_size: "32k"
    nginx_proxy_http2_max_header_size: "32k"
    plugins: bundled,pep-plugin,ngsi-ishare-policies
    pluginserver_names: pep-plugin
    pluginserver_pep_plugin_start_cmd: "/go-plugins/pep-plugin"
    pluginserver_pep_plugin_query_cmd: "/go-plugins/pep-plugin -dump"

  ingressController:
    enabled: false
    installCRDs: false
  
  proxy:
    type: ClusterIP
    enabled: true
    tls:
      enabled: false
      
    # Provide Ingress or Route config here
    ingress:
      enabled: false
    route:
      enabled: false
  
  admin:
    enabled: true
    type: ClusterIP  
    http: 
      enabled: true
      servicePort: 8001
      containerPort: 8001

  status:
    enabled: true
    http: 
      enabled: true
      containerPort: 9102

  # Provide the kong.yml configuration (either as existing CM, secret or directly in the values.yaml)
  dblessConfig:
    configMap: ""
    secret: ""
    config: |
      _format_version: "2.1"
      _transform: true

      consumers:
      - username: token-consumer
        keyauth_credentials:
        - tags: 
          - token-key
          - tir-key

      services:
        - host: "orion"
          name: "provider"
          port: 1026
          protocol: http

          routes:
            - name: my-path
              paths:
                - /my-path
              strip_path: true

          plugins:
            - name: pep-plugin
              config:
                pathprefix: "/pdc"
                authorizationendpointtype: ExtAuthz
                authorizationendpointaddress: http://pdp-dsba-pdp:8080/authz

            - name: request-transformer
              config:
                remove:
                  headers:
                    - Authorization
                    - authorization
