keyrock:
  fullnameOverride: keyrock-dsc

  # Image
  statefulset:
    image:
      repository: quay.io/wi_stefan/keyrock
      tag: sn-fix-2
      pullPolicy: Always

  # DB config
  db:
    user: root
    password: "<mysql-password>"
    host: mysql-dsc

  # Admin user to be created
  admin:
    user: admin
    password: "<keyrock-password>"
    email: admin@fiware.org

  # External hostname of Keyrock
  host: https://keyrock.provider.com
  
  ## Theme configuration for Keyrock
  theme:
    ## -- Enable theme
    enabled: false

  ## Configuration of Authorisation Registry (AR)
  authorisationRegistry:
    # -- Enable usage of authorisation registry
    enabled: true
    # -- Identifier (EORI) of AR
    identifier: "did:web:my-did:did"
    # -- URL of AR
    url: "internal"

  ## Configuration of iSHARE Satellite
  satellite:
    # -- Enable usage of satellite
    enabled: true
    # -- Identifier (EORI) of satellite
    identifier: "EU.EORI.FIWARESATELLITE"
    # -- URL of satellite
    url: "https://tir.dataspace.com"
    # -- Token endpoint of satellite
    tokenEndpoint: "https://https://tir.dataspace.com/token"
    # -- Parties endpoint of satellite
    partiesEndpoint: "https://https://tir.dataspace.com/parties"

  ## -- Configuration of local key and certificate for validation and generation of tokens
  token:
    # -- Enable storage of local key and certificate
    enabled: false

  # ENV variables for Keyrock
  additionalEnvVars:
    - name: IDM_TITLE
      value: "dsba AR"
    - name: IDM_DEBUG
      value: "true"
    - name: DEBUG
      value: "*"
    - name: IDM_DB_NAME
      value: ar_idm
    - name: IDM_DB_SEED
      value: "true"
    - name: IDM_SERVER_MAX_HEADER_SIZE
      value: "32768"
    - name: IDM_PR_CLIENT_ID
      value: "did:web:my-did:did"
    - name: IDM_PR_CLIENT_KEY
      valueFrom:
          secretKeyRef:
            name: vcwaltid-tls-sec
            key: tls.key
    - name: IDM_PR_CLIENT_CRT
      valueFrom:
          secretKeyRef:
            name: vcwaltid-tls-sec
            key: tls.crt
