vcverifier:
  
  deployment:

    # Image
    image:
      repository: quay.io/fiware/vcverifier
      tag: 4.3.1
      pullPolicy: Always

    # Logging
    logging: 
      level: DEBUG
      pathsToSkip: 
        - "/health"

    # Server config
    #server:
    #  # Place external host here when publishing verifier with public URL
    #  host: https://verifier.my-url.com

    # Walt-id config
    ssikit:
      auditorUrl: http://vcwaltid:7003

    # Verifier config
    verifier:
      # URL endpoint of data space trusted issuers registry
      tirAddress: https://tir.dataspace.com/v3/issuers
      # DID of organisation
      did: did:web:my-did:did

    # M2M config
    m2m:
      authEnabled: false

    # Config service
    configRepo:
      configEndpoint: http://ccs-credentials-config-service:8080/
